image: node:14
pipelines:
  branches:
    release/development:
      - step:
          name: Build and Push to App Engine
          script:
          # Set a couple variables for readability
          - SDK_VERSION=197.0.0
          - SDK_FILENAME=google-cloud-sdk-${SDK_VERSION}-linux-x86_64.tar.gz
          # Install Google Cloud SDK
          - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${SDK_FILENAME}
          - tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
          - /tmp/google-cloud-sdk/install.sh -q
          - source /tmp/google-cloud-sdk/path.bash.inc
          - gcloud -v
          - echo ${GOOGLE_CLIENT_SECRET} > client-secret.json
          - npm install
          - npm run build
          - gcloud auth activate-service-account --key-file client-secret.json
          - gcloud --verbosity=error app deploy app.yaml --promote --project ${GOOGLE_PROJECT_NAME} 
    release/production:
      - step:
          name: Build and Push to App Engine Prod
          script:
          # Set a couple variables for readability
          - SDK_VERSION=197.0.0
          - SDK_FILENAME=google-cloud-sdk-${SDK_VERSION}-linux-x86_64.tar.gz
          # Install Google Cloud SDK
          - curl -o /tmp/google-cloud-sdk.tar.gz https://dl.google.com/dl/cloudsdk/channels/rapid/downloads/${SDK_FILENAME}
          - tar -xvf /tmp/google-cloud-sdk.tar.gz -C /tmp/
          - /tmp/google-cloud-sdk/install.sh -q
          - source /tmp/google-cloud-sdk/path.bash.inc
          - gcloud -v
          - echo ${GOOGLE_CLIENT_SECRET} > client-secret.json
          - npm install
          - npm run build
          - gcloud auth activate-service-account --key-file client-secret.json
          - gcloud --verbosity=error app deploy app.yaml --promote --project ${GOOGLE_PROJECT_NAME} 
